run:
  go: "1.23"
  tests: true

linters:
  # The default behavior of golangci-lint IS to run the default set of linters
  # when no 'enable' or 'preset' is specified. So we can remove the 'presets'
  # block and just specify which of the default linters to disable.

  disable:
    - errcheck
    - staticcheck
    - unused

issues:
  # The name for this section in v1.59.1 is 'exclude-rules'.
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck # For example, you might not want to check errors in tests.
